pipeline:
  name: test
  identifier: test
  projectIdentifier: HarnessCICD
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: git
        build: <+input>
  stages:
    - stage:
        name: dev
        identifier: dev
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build_Backend
                  identifier: Build_Backend
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.9-eclipse-temurin-21
                    shell: Sh
                    command: |-
                      java -version
                      mvn -version
                      cd backend
                      mvn -B -ntp clean package -DskipTests
                      ls -l target/*.jar
