pipeline:
  name: test
  identifier: test
  projectIdentifier: HarnessCICD
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: git
        build: <+input>
  stages:
    - stage:
        name: dev
        identifier: dev
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      # set -e
                      #    ls -la
                      #    java -version
                      #    mvn -version
                      #    cd backend
                      #    mvn -B clean package
                      #    ls -l target/*.jar
                      ls -l
                      java --version
                      mvn --version
                      cd backend   
                      mvn -B clean package
                      ls -l target/*.jar
