replicaCount: 1

frontend:
  image:
    repository: 654654241151.dkr.ecr.us-east-1.amazonaws.com/demo-app
    tag: "frontend-b014b4b"

backend:
  image:
    repository: 654654241151.dkr.ecr.us-east-1.amazonaws.com/demo-app
    tag: "backend-b014b4b"

postgres:
  image: postgres:14
  storage:
    size: 5Gi
    storageClass: gp3
